### ISSUE TITLE
Errors creating cluster

### ISSUE THREAD

**Issue by idc101** [microsoft/azure-databricks-operator#120]
We see these errors reconciling clusters:

```
2019-11-24T23:19:58.371Z        ERROR   controller-runtime.controller   Reconciler error        {"controller": "dcluster", "request": "dx/interactive-always-on-nopassthrough", "error": "err
or when refreshing cluster: unexpected end of JSON input"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:171
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
```

Here is the YAML:
```
apiVersion: databricks.microsoft.com/v1alpha1
kind: Dcluster
spec:
  autotermination_minutes: 120
  cluster_name: interactive-always-on-nopassthrough
  custom_tags:
  - key: ResourceClass
    value: Serverless
  driver_node_type_id: Standard_D3_v2
  enable_elastic_disk: true
  init_scripts:
  - dbfs:
      destination: dbfs:/databricks/init_scripts/openssl_fix.sh
  - dbfs:
      destination: dbfs:/databricks/init_scripts/log_analytics/listeners.sh
  node_type_id: Standard_D3_v2
  num_workers: 5
  spark_conf:
    spark.databricks.cluster.profile: serverless
    spark.databricks.delta.preview.enabled: "true"
    spark.databricks.repl.allowedLanguages: sql,python
    spark.hadoop.hive.server2.enable.doAs: "false"
  spark_env_vars:
    PYSPARK_PYTHON: /databricks/python3/bin/python3
  spark_version: latest-stable-scala2.11
status:
  cluster_info:
    cluster_cores: "0"
    cluster_id: 1113-043420-odors235
```
