### ISSUE TITLE
Add cluster name support for dbricks run

### ISSUE THREAD

**Issue by Azadehkhojandi** [microsoft/azure-databricks-operator#142]
currently, you can submit run on existing cluster by providing existing_cluster_id
```
apiVersion: databricks.microsoft.com/v1alpha1
kind: Run
metadata:
  name: drun-twitteringest1
spec:
  # create a run directly without a job
  existing_cluster_id: 1021-013622-bused793
```

You should be able to  submit run on existing cluster by providing existing_cluster_name

```
apiVersion: databricks.microsoft.com/v1alpha1
kind: Run
metadata:
  name: drun-twitteringest1
spec:
  # create a run directly without a job
  existing_cluster_name: dcluster-interactive2
```
