### ISSUE TITLE
dcluster doesn't show the STATE and  NUMWORKERS

### ISSUE THREAD

**Issue by Azadehkhojandi** [microsoft/azure-databricks-operator#93]
How to replicate: 
Use below Yaml file
 
```
---
apiVersion: databricks.microsoft.com/v1alpha1
kind: Dcluster
metadata:
  name: interactive-cluster-1
spec:
  spark_version: latest-stable-scala2.11
  node_type_id: Standard_D3_v2
  autoscale:
    min_workers: 1
    max_workers: 6
  driver_node_type_id: Standard_D3_v2
  custom_tags:
  - key: Tag
    value: CustomTag1
  spark_env_vars:
    PYSPARK_PYTHON: /databricks/python3/bin/python3
  enable_elastic_disk: true

```
the run `kubectl apply -f docs/samples/2_job_rub/interactive-cluster1.yaml`
```
kubectl get dcluster                         
NAME                    AGE    CLUSTERID             STATE   NUMWORKERS
interactive-cluster-2   110m   1018-033048-slew898     
```      

then run `kubectl get dcluster`
